config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :articles do
		resources :comments
		member do
			put 'add_vote'
			put 'favorating'
			put 'unfavorating'
		end
		collection do
			get 'descending'
			get 'ascending'
			get 'up'
			get 'down'
			get 'timeup'
			get 'timedown'
		end
	end
	resources :labels
	mount Sidekiq::Web => 'sidekiq／cron'
	resources :users, path: :managers do
		member do
			put 'active'
			put 'unactive'
			put 'sign_in'
		end
		collection do
			put 'activeall'
			put 'unactiveall'
		end
	end
	resources :favorites, only: [:index]
	resources :pictures
	resources :messages
	root "articles#index"
	namespace :account do
   resources :comments
	 resources :articles
  end
end

app/models/favorite.rb
class Favorite
  include Mongoid::Document
  include Mongoid::Timestamps
  field :username, type: String
  field :article_title, type: String
  belongs_to :user
  belongs_to :article
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    @favorites = current_user.favorites
  end

  private

end

app/views/favorites/index.html.erb
<div class="col-md-10">
  <div class="pull-right">
    <%= link_to "返回首页", articles_path, class: "btn btn-primary btn-xs" %>
  </div>
  <table class="table table-bordered">
    <thead>
     <tr>
        <th>Title</th>
        <th>username </th>
        <th>状态</th>
     </tr>
    </thead>
    <tbody>
      <% @favorites.each do |favorite| %>
        <tr>
          <td><%= link_to favorite.article_title, article_path(favorite.article_id) %></td>
          <td><%= favorite.username %></td>
          <td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/favorites/new.html.erb
<div class="col-md-8">
  <h2>创建站内信</h2>
  <%= simple_form_for @message do |f| %>
    <%= f.input :title, label: "站内信标题" %>
    <%= f.input :content, label: "站内信内容"%>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/favorites/show.html.erb
<div class="col-md-8">
  <div class="pull-right">
    <%= link_to "返回站内信首页", messages_path, class: "btn btn-primary btn-xs" %>
  </div>
    <h2><%= @message.title %></h2>
    <p><%= @message.content %></p>
</div>