config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :articles do
		resources :comments
		member do
			put 'add_vote'
			put 'favorating'
			put 'unfavorating'
		end
		collection do
			get 'descending'
			get 'ascending'
			get 'up'
			get 'down'
			get 'timeup'
			get 'timedown'
		end
	end
	resources :labels
	mount Sidekiq::Web => 'sidekiq／cron'
	resources :users, path: :managers do
		member do
			put 'active'
			put 'unactive'
			put 'sign_in'
		end
		collection do
			put 'activeall'
			put 'unactiveall'
		end
	end
	resources :favorites, only: [:index]
	resources :pictures
	resources :messages
	root "articles#index"
	namespace :account do
   resources :comments
	 resources :articles
  end
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :image, ImageUploader
  field :title, type: String
  field :content, type: String
  field :from, type: String
  field :url, type: String
  field :read_number, type: Integer
  field :vote, type: Integer, default: 0
  validates_presence_of :title, message: "标题不能为空"
  validates_presence_of :url, message: "来源不能为空"

  belongs_to :user
  has_and_belongs_to_many :labels
  has_and_belongs_to_many :pictures
  has_many :comments
  field :favorate, type: Boolean, default: false
  has_many :favorites
end

app/controllers/account/articles_controller.rb
class Account::ArticlesController < ApplicationController
  before_action :authenticate_user!
  def index
    @articles = current_user.articles.where(favorate: true)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  layout 'admin'

  def index
    @articles = Article.all.order_by( :created_at => 'desc').includes(:user,:labels, :pictures)
    @articles = @articles.where(title: /#{params[:title]}/) unless params[:title].blank?
    @articles = @articles.where(content: /#{params[:content]}/) unless params[:content].blank?
  end

  def new
    @labels = Label.all.map { |label| [label.name, label.id.to_s] }
    @pictures = Picture.all.map { |picture| [picture.photo, picture.id.to_s]}
    @pictures = @pictures.where(name: /#{params[:name]}/) unless params[:name].blank?
    @pictures = @pictures.where(type: /#{params[:type]}/) unless params[:type].blank?
  end

  def create
    @article = current_user.articles.build(article_params)
    selected_labels = Label.in(id: params["checked_labels"].try(:values))
    @article.labels << selected_labels
    selected_pictures = Picture.in(id: params["checked_pictures"].try(:values))
    @article.pictures << selected_pictures
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @labels = Label.all.map { |label| [label.name, label.id.to_s] }
  end

  def update
    selected_labels = Label.in(id: params["checked_labels"].try(:values))
    @article.labels << selected_labels
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def add_vote
    @article = Article.find(params[:id])
    @article.vote += 2
    @article.save
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end
  def show
    @comments = @article.comments
    @comment = Comment.new
  end
  def descending
    @articles = Article.all
    @articles = @articles.order_by(:read_number => 'desc')
    render :index
  end
  def ascending
    @articles = Article.all
    @articles = @articles.order_by(:read_number => 'asc')
    render :index
  end
  def down
    @articles = Article.all
    @articles = @articles.order_by(:vote => 'desc')
    render :index
  end
  def up
    @articles = Article.all
    @articles = @articles.order_by(:vote => 'asc')
    render :index
  end
  def timedown
    @articles = Article.all
    @articles = @articles.order_by(:created_at => 'desc')
    render :index
  end
  def timeup
    @articles = Article.all
    @articles = @articles.order_by(:created_at => 'asc')
    render :index
  end
  def favorating
    @article = Article.find(params[:id])
    @favorite = current_user.favorites.create(article: @article, article_title: @article.title, username: @current_user.email)
    redirect_to article_path(@article)
  end
  def unfavorating
    @article.update(favorate: false)
    redirect_to article_path(@article)
  end
  private
  def article_params
    params.require(:article).permit(:title, :content, :from, :url, :read_number, :image, :vote)
  end
end

app/helpers/account/articles_helper.rb
module Account::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="col-md-8">
  编辑文章
  <%= simple_form_for @article do |f| %>
    <%= f.input :title, label: "文章标题" %>
    <%= f.input :content,label: "文章内容" %>
    <%= f.input :from, label: "from" %>
    <%= f.input :url, label: "url" %>
    <%= f.input :read_number, label: "点击次数" %>
    <%= f.input :image %>
    <div class="form-group string required article_title">
     <label class="col-sm-2 control-label string required" for="article_title">
      选择标签</label>
      <div class="col-sm-10">
        <% @labels.each_with_index do |label, index| %>
           <input id="" name="checked_labels[<%= index %>]" type="checkbox" value="<%= label[1] %>" <%= @article.labels.find(label[1]).nil? ? '' : 'checked' %> />
           <label for="pet_dog"><%= raw label[0] %></label>
        <% end %>
      </div>
   </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="col-md-10">
  <div class="pull-left">
      <%= link_to "控制面板",  sidekiq_web_path, class: "btn btn-danger"%>
      <%= link_to "账号管理", users_path, class: "btn btn-danger" %>
      <%= link_to "标签管理", labels_path, class: "btn btn-danger" %>
      <%= link_to "图片管理", pictures_path, class: "btn btn-danger" %>
      <p>用户积分：</p><%= current_user.credit %>
       <% if current_user.credit_logs.between(created_at: [Date.today.beginning_of_day, Date.today.end_of_day]).any? %>
          <p>已经签到</p>
       <% else %>
          <%= link_to("签到", sign_in_user_path(current_user, page: params[:page]), method: :put, class: "btn btn-success btn-xs") %>
       <% end %>
  </div>
  <div class="text-center">
    <form action="/articles" method="get">
      标题
      <input type="text" id='title' name="title" value="<%= params[:title]%>">
      内容
      <input type="text" id='content' name="content" value="<%= params[:content]%>" >
      <input type="submit" name="" value="搜索">
    </form>
  </div>

  <div class="pull-right">
    <%= link_to "新建文章", new_article_path, class: "btn btn-primary btn-xs" %>
  </div>
  <table class="table table-bordered">
    <thead>
     <tr>
        <th>Title</th>
        <th>From</th>
        <th>Url</th>
        <th width=100px>
          Readnumber
           <%= link_to descending_articles_path  do  %>
               <i class="fa fa-sort-amount-desc" aria-hidden="true"></i>
           <% end %>
           <%= link_to ascending_articles_path  do  %>
               <i class="fa fa-sort-amount-asc" aria-hidden="true"> </i>
           <% end %>
        </th>
        <th>采集者</th>
        <th>
          创建时间
          <%= link_to timedown_articles_path  do  %>
              <i class="fa fa-sort-amount-desc" aria-hidden="true"></i>
          <% end %>
          <%= link_to timeup_articles_path  do  %>
              <i class="fa fa-sort-amount-asc" aria-hidden="true"> </i>
          <% end %>
        </th>
        <th>标签</th>
        <th>图片</th>
        <th>操作</th>
        <th>投票</th>
        <th>
          票数:
          <%= link_to down_articles_path  do  %>
              <i class="fa fa-sort-amount-desc" aria-hidden="true"></i>
          <% end %>
          <%= link_to up_articles_path  do  %>
              <i class="fa fa-sort-amount-asc" aria-hidden="true"> </i>
          <% end %>
        </th>

     </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to(article.title, article_path(article))%></td>
          <td><%= article.from %></td>
          <td><%= article.url %></td>
          <td><%= article.read_number %></td>
          <td><%= article.user&.email %></td>
          <td><%= article.created_at.strftime("%Y/%m/%d %I:%M %p") %></td>
          <td>
                <% article.labels.each do |l| %>
                   <%= raw l.name %>
                <% end %>
          </td>
          <td>
            <% article.pictures.each do |p| %>
                  <%= raw p.photo %>
                  <%= image_tag(p.photo.url("720x240"), class: "thumbnail") %>
            <% end %>
          </td>
          <td>
            <%= link_to("edit", edit_article_path(article))%>
            <%= link_to("show", article_path(article))%>
            <%= link_to("delete", article_path(article), method: :delete)%>
          </td>
          <td><%= article.vote %></td>
          <td><%= link_to("投票", add_vote_article_path(article), method: :put, class: "btn btn-sm btn-danger")%></td>
        </tr>
       <% end %>
    </tbody>
  </table>
</div>

app/views/articles/new.html.erb
<div class="col-md-8">
  <%= @article&.errors&.full_messages %>
  创建文章
  <%= simple_form_for @article do |f| %>
    <%= f.input :title, label: "文章标题" %>
    <%= f.input :content,label: "文章内容" %>
    <%= f.input :from, label: "from" %>
    <%= f.input :url, label: "url" %>
    <%= f.input :read_number, label: "点击次数" %>
    <%= f.label :label_id %>
    <%= f.input :image, label: "上传图片"%>
    <div class="form-group string required article_title">
    <label class="col-sm-2 control-label string required" for="article_title">
      选择标签</label>
    <div class="col-sm-10">
        <% @labels.each_with_index do |label, index| %>
         <input id="" name="checked_labels[<%= index %>]" type="checkbox" value="<%= label[1] %>"
               <%= @article.labels.find(label[1]).nil? ? '' : 'checked' %> />
         <label for="pet_dog"><%= raw label[0] %></label>
       <% end %>
      </div>
    </div>
    <div class="text-center">
     <form action="/pictures" method="get">
        图片名字
        <input type="text" id="name" name="name" value="<%= params[:name]%>">
        图片类型
        <input type="text" id="type" name="type" value="<%= params[:type]%>">
        <input type="submit" name="" value="搜索">
     </form>
    <div class="form-group string required article_title">
    <label class="col-sm-2 control-label string required" for="article_title">
      从图库中选择图片</label>
      <div class="col-sm-10">
        <% @pictures.each_with_index do |picture, index| %>
         <input id="" name="checked_pictures[<%= index %>]" type="checkbox" value="<%= picture[1] %>"
               <%= @article.pictures.find(picture[1]).nil? ? '' : 'checked' %> />
         <label for="pet_dog">
           <!-- <%= raw picture[0]  %> -->
           <!-- <%= image_tag(picture[0], class: "thumbnail") %> -->
            <img src="<%= picture[0].url('720x240') %>">
         </label>
       <% end %>
      </div>
    </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="col-md-7">
    <h2><%= @article.title %>
      <div class="pull-right">
        <% if current_user.favorites.find_by(article: @article) %>
          <%= link_to("取消收藏", unfavorating_article_path, method: :put,  class: "btn btn-sm btn-info")%>
        <% else %>
          <%= link_to("收藏", favorating_article_path, method: :put, class: "btn btn-sm btn-info")%>
        <% end %>
      </div>
    <p><%= @article.content %></p>
    <br>
    <% if @article.image_url %>
    <%= @article.image_url("720x240") %>
      <%= image_tag(@article.image_url("720x240"), class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
    <% end %>
    <%= link_to("Download Image", @article.image_url)%>
    <br>
    <div class="pull-left">
      <%= link_to("写评论", new_article_comment_path(@article), class: "btn btn-sm btn-primary")%>
    </div>
    <div class="col-md-4 col-md-offset-4">
      <%= simple_form_for [@article,@comment] do |f| %>
        <%= f.input :content, label: "写评论"%>
        <%= f.submit "提交", class: "btn btn-sm btn-primary" %>
      <% end %>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Content</th>
          <th>Writer</th>
          <th>Create Time</th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.content %></td>
          <td><%= comment.user.email %></td>
          <td><%= comment.created_at.strftime("%F %T") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>