config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :articles do
		resources :comments
		member do
			put 'add_vote'
			put 'favorating'
			put 'unfavorating'
		end
		collection do
			get 'descending'
			get 'ascending'
			get 'up'
			get 'down'
			get 'timeup'
			get 'timedown'
		end
	end
	resources :labels
	mount Sidekiq::Web => 'sidekiq／cron'
	resources :users, path: :managers do
		member do
			put 'active'
			put 'unactive'
			put 'sign_in'
		end
		collection do
			put 'activeall'
			put 'unactiveall'
		end
	end
	resources :favorites, only: [:index]
	resources :pictures
	resources :messages
	root "articles#index"
	namespace :account do
   resources :comments
	 resources :articles
  end
end

app/models/label.rb
class Label
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  has_and_belongs_to_many :articles
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
   def index
     @labels = Label.all
   end
   def new
   end
   def create
     if @label.save
       redirect_to labels_path
     else
       render :new
     end
   end
   def edit
   end
   def update
     if @label.update(label_params)
       redirect_to labels_path
     else
       render :edit
     end
   end
   def destroy
     @label.destroy
     redirect_to labels_path
   end
   def show
   end
   private
   def label_params
     params.require(:label).permit(:name)
   end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/index.html.erb
<div class="col-md-10">
  <div class="pull-right">
    <%= link_to "返回首页", articles_path, class: "btn btn-primary btn-xs" %>
    <%= link_to "新建标签", new_label_path, class: "btn btn-primary btn-xs"%>
  </div>
  <table class="table table-bordered">
    <thead>
     <tr>
        <th>Name</th>
        <th></th>
     </tr>
    </thead>
    <tbody>
      <% @labels.each do |label| %>
        <tr>
          <td><%= label.name %></td>
          <td>
            <%= link_to("edit", edit_label_path(label))%>
            <%= link_to("show", label_path(label))%>
            <%= link_to("delete", label_path(label), method: :delete)%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/labels/new.html.erb
<div class="col-md-8">
  创建标签
  <%= simple_form_for @label do |f| %>
    <%= f.input :name, label: "标签名字" %>
    <%= f.submit "Submit" %>
  <% end %>
</div>