config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :articles do
		resources :comments
		member do
			put 'add_vote'
			put 'favorating'
			put 'unfavorating'
		end
		collection do
			get 'descending'
			get 'ascending'
			get 'up'
			get 'down'
			get 'timeup'
			get 'timedown'
		end
	end
	resources :labels
	mount Sidekiq::Web => 'sidekiq／cron'
	resources :users, path: :managers do
		member do
			put 'active'
			put 'unactive'
			put 'sign_in'
		end
		collection do
			put 'activeall'
			put 'unactiveall'
		end
	end
	resources :favorites, only: [:index]
	resources :pictures
	resources :messages
	root "articles#index"
	namespace :account do
   resources :comments
	 resources :articles
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :username, type: String
  mount_uploader :userphoto, UserphotoUploader
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  has_many :articles

  field :active, type: Boolean, default: false
  field :role,              type: String
  ROLES = [:admin, :user, :collecter]
  def admin?
    role == 'admin'
  end
  field :credit, type: Integer, default: 0
  has_many :credit_logs
  def sign
    if self.credit_logs.between(created_at: [Date.today.beginning_of_day, Date.today.end_of_day]).any?
    else
      add_credit = rand(10)
      self.inc(credit: add_credit)
      self.credit_logs.create(credit: add_credit, type: "用户签到")
    end
  end
  has_many :comments
  has_many :favorites
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
     @users = User.all.page params[:page]
     @users = @users.where(email: /#{params[:email]}/) unless params[:email].blank?
     @users = @users.where(username: /#{params[:username]}/) unless params[:username].blank?
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def activeall
    User.update_all(active: true)
    redirect_to  users_path
  end

  def unactiveall
    User.update_all(active: false)
    redirect_to  users_path
  end

  def active
    @user = User.find(params[:id])
    @user.update(active: true)
    redirect_to users_path
  end

  def unactive
    @user = User.find(params[:id])
    @user.update(active: false)
    redirect_to users_path
  end

  def sign_in
    @user = User.find(params[:id])
    if @user.sign
      flash[:notice] = "aaaa"
    else
      flash[:notice] = "xxxx"
    end
    redirect_to articles_path(page: params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :userphoto, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="col-md-10">
  <div class="pull-right">
    <%= link_to "new", new_user_path %>
    <%= link_to "一键激活", activeall_users_path, method: :put, class: "btn btn-success btn-xs"%>
    <%= link_to "一键关闭", unactiveall_users_path, method: :put, class: "btn btn-success btn-xs"%>
  </div>
  <div class="text-center">
    <form action="/managers" method="get">
      email
      <input type="text" id='email' name="email" value="<%= params[:email]%>">
      username
      <input type="text" id='username' name="username" value="<%= params[:username]%>">
      <input type="submit" name="" value="搜索">
    </form>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>邮箱</th>
        <th>状态</th>
        <th>用户名</th>
        <th>角色</th>
        <th>积分</th>
        <th>签到情况</th>
        <th>积分纪录</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
          <td><%= user.email %></td>
          <td><%= user.active %></td>
          <td><%= user.username %></td>
          <td><%= user.role %></td>
          <td><%= user.credit %></td>
         <td>
           <% if user.credit_logs.between(created_at: [Date.today.beginning_of_day, Date.today.end_of_day]).any? %>
              <p>已经签到</p>
           <% else %>
              <%= link_to("签到", sign_in_user_path(user, page: params[:page]), method: :put, class: "btn btn-success btn-xs") %>
           <% end %>
        <td>


            <div class="col-md-7">
                <% if user.userphoto_url %>
                <%= user.userphoto_url("720x240") %>
                  <%= image_tag(user.userphoto_url("720x240"), class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
                <% end %>
                <%= link_to("Download Image", user.userphoto_url)%>
            </div>
          </td>
          <td>
            <%= link_to "edit", edit_user_path(user)%>
          </td>
          <td>
            <% if user.active %>
              <%= link_to("取消激活", unactive_user_path(user), method: :put, class: "btn btn-warning btn-xs") %>
            <% else %>
               <%= link_to("激活", active_user_path(user), method: :put, class: "btn btn-success btn-xs") %>
            <% end %>
          </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<div class="col-md-offset-2">
  <%= simple_form_for(@user, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :email, label: "邮箱" %>
    <%= f.input :username, label: "用户名" %>
    <%= f.input :password, label: "密码" %>
    <%= f.input :password_confirmation, label: "确认密码" %>
    <%= f.input :userphoto %>
    <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.button :submit, "提 交", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>